defaults: &defaults
  docker:
    - image: circleci/node:8
  working_directory: ~/blog

version: 2
jobs:
  pre-build:
    <<: *defaults
    steps:
      - checkout:
        path: ~/blog/
      - attach_workspace:
        at: ~/blog/
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/blog
          paths:
            - node_modules
  test:
    <<: *defaults
    steps:
      - checkout:
        path: ~/blog/
      - attach_workspace:
        at: ~/blog/
      - run: npm run test
  
  deploy:
    <<: *defaults
    steps:
      - checkout:
        path: ~/blog/
      - attach_workspace:
        at: ~/blog/
      - run:
        command: |
          sudo apt-get -y -qq install awscli
          CI=false npm run build:ci
          aws s3 sync public/ s3://loudcoder.com  --region ap-southeast-2 --delete